### ISSUE TITLE
Time Column Issue?

### ISSUE THREAD

**Issue by alinscodes** [Blasterai/codaio#49]
I have a table with a time column.
![image](https://user-images.githubusercontent.com/47319414/143596709-233c5874-7dcf-4259-8d66-1402a5970f43.png)

When I read it using API, I get a time like "1899-12-30T06:52:00.000-08:00" and I am not sure why.

**Comment by licht1stein** [comment]
Hi @alinscodes 

It's probably a bug on the Coda side, they're returning a full date-time object instead of just time. Luckily, it's quite easy to convert to time, since the string is standard ISO format with miliseconds:

```python
from datetime import datetime
from datetime import timezone


time_string = "1899-12-30T06:52:00.000-08:00" 
date = datetime.fromisoformat(time_string.replace(".000", ""))
time = date.astimezone(tz=timezone.utc).time()
```

This will get you a time object as UTC. To make your life easier you can use the amazing [pendulum](https://pendulum.eustace.io/) package to work with times. Then you'll just be able to run `parse`, and then quickly get time as any timezone you want.

**Comment by licht1stein** [comment]
It is a Coda bug, I found an older issue: https://github.com/Blasterai/codaio/issues/39
